version: '3'

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: movies_db_backend_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: